site_name: PSEnv Documentation
site_description: A tool for managing AWS Parameter Store environments
site_url: https://yourdomain.com/
repo_url: https://github.com/pytoolbelt/psenv
repo_name: psenv

theme:
  name: material
  logo: assets/logo-noBgColor.png
  palette:
    primary: 07689f
    accent: ff7e67
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage:
      - Configuration: usage/configuration.md
      - Commands: usage/commands.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
